name: Check master and artifact binary sizes
description: Check master and artifact binary sizes for Godot artifacts.
inputs:
  name:
    description: The artifact name.
    default: "${{ github.job }}"
runs:
  using: "composite"
  steps:
    - name: Compare binary size with latest successful master build
      shell: bash
      run: |
        if [[ "$RUNNER_OS" == "macOS" ]]; then
          echo "Running on macOS, exiting..."
          exit 0
        fi

        echo "Current commit: $(git rev-parse HEAD)"

        template_name=$(echo ${{ github.job }} | sed 's/[^a-zA-Z0-9_]/_/g')
        template=${template_name//-/_}

        file_path="$GITHUB_WORKSPACE/bin/*"

        if [ ! -d "${file_path}" ]; then
          echo "Directory ${file_path} does not exist, exiting..."
          exit 0
        fi

        actual_size=$(du -sb "$file_path" | awk '{print $1}')

        last_artifact_file="./last_artifact/${{ github.job }}"
        if [[ -d "$last_artifact_file" ]]; then
          expected_size=$(du -sb "$last_artifact_file" | awk '{print $1}')
        else
          echo "No previous artifact found for comparison."
          exit 0
        fi

        size_difference=$((actual_size - expected_size))

        if [[ $size_difference -ge 1 ]]; then
          echo -e "\033[1mBinary size:\033[0m The $template binary is \033[1;91m$size_difference bytes larger\033[0m than the last successful commit."
        elif [[ $size_difference -lt 0 ]]; then
          echo -e "\033[1mBinary size:\033[0m The $template binary is \033[1;92m$size_difference bytes smaller\033[0m than the last successful commit."
        else
          echo -e "\033[1mBinary size:\033[0m The $template binary is \033[1;92mexactly as the last successful commit.\033[0m"
